accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

photo/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ImageListView
# URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

# URLパターンを登録する変数
urlpatterns = [
     # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
     path('', views.IndexView.as_view(), name='index'),
     path('post/',views.CreatePhotoView.as_view(),name='post'),
     path('post_done/',
          views.PostSuccessView.as_view(),
          name='post_done'),
     path('photos/<int:category>',
          views.CategoryView.as_view(),
          name='photos_cat'
          ),
     path('user-list/<int:user>',
          views.UserView.as_view(),
          name='user_list'
          ),
     path('photo-detail/<int:pk>',
          views.DetailView.as_view(),
          name='photo_detail'
          ),
     path('mypage/',views.MypageView.as_view(),name='mypage'),
     path('photo/<int:pk>/delete/',
          views.PhotoDeleteView.as_view(),
          name='photo_delete'
          ),
     path(
          'contact/',
          views.ContactView.as_view(),
          name='contact'),
     path(
          'favorite/',
          views.FavoriteView.as_view(),
          name='favorite'),
     path(
          'In_detail/',
          views.InDetailView.as_view(),
          name='In_detail'),
     path('gallery/',
          views.image_gallery,
          name='image_gallery'),
     path('images/', ImageListView.as_view(), name='image_list'),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views
from photo import views
urlpatterns = [
    path('admin/', admin.site.urls),
    # photo.urlsへのURLパターン
    path('', include('photo.urls')),
    
    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),
    
    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]

photo/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    title = models.CharField(verbose_name='カテゴリ', max_length=20)
    def __str__(self):
        return self.title


class PhotoPost(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='カテゴリ', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=200)
    comment = models.TextField(verbose_name='コメント')
    image1 = models.ImageField(verbose_name='イメージ1', upload_to='photos')
    image2 = models.ImageField(verbose_name='イメージ2', upload_to='photos', blank=True, null=True)
    image3 = models.ImageField(verbose_name='イメージ3', upload_to='photos', blank=True, null=True)
    image4 = models.ImageField(verbose_name='イメージ4', upload_to='photos', blank=True, null=True)
    posted_at = models.DateTimeField(verbose_name='投稿日時', auto_now_add=True)
    
    def __str__(self):
        return self.title

from django.db import models

class Type(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Rarity(models.Model):
    level = models.CharField(max_length=50)

    def __str__(self):
        return self.level

class ImageModel(models.Model):
    name = models.CharField(max_length=100)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    rarity = models.ForeignKey(Rarity, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)  # カテゴリを追加
    image = models.ImageField(upload_to='image_poke/')

    def __str__(self):
        return self.name

photo/forms.py
from django import forms
from .models import PhotoPost

class PhotoPostForm(forms.ModelForm):
    class Meta:
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2', 'image3', 'image4']






class ContactForm(forms.Form):
    
    name=forms.CharField(label='お名前')
    email=forms.EmailField(label='メールアドレス')
    title=forms.CharField(label='件名')
    message=forms.CharField(label='メッセージ',widget=forms.Textarea)
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args,**kwargs)
        
        self.fields['name'].widget.attrs['placeholder']=\
            'お名前を入力してください'
        self.fields['name'].widget.attrs['class']='form-control'
        
        self.fields['email'].widget.attrs['placeholder']=\
            'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class']='form-control'
        
        self.fields['title'].widget.attrs['placeholder']=\
            'タイトルを入力してください'   
        self.fields['title'].widget.attrs['class']='form-control'
        
        self.fields['message'].widget.attrs['placeholder']=\
            'メッセージを入力してください'
        self.fields['message'].widget.attrs['class']='form-control'


# forms.py
from django import forms
from .models import Type, Rarity, Category

class ImageSearchForm(forms.Form):
    name = forms.CharField(required=False, label='名前')
    type = forms.ModelChoiceField(queryset=Type.objects.all(), required=False, label='タイプ')
    rarity = forms.ModelChoiceField(queryset=Rarity.objects.all(), required=False, label='レアリティ')
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False, label='カテゴリ')

photo/views.py
from django.views.generic import ListView, CreateView, DetailView, DeleteView, TemplateView, FormView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.contrib import messages
from .forms import PhotoPostForm, ContactForm
from .models import PhotoPost
from django.shortcuts import render
from django.core.paginator import Paginator
from .utils import get_local_images

class IndexView(ListView):                                  #index
    template_name = 'index.html'
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9

@method_decorator(login_required, name='dispatch')          #post
class CreatePhotoView(CreateView):
    form_class = PhotoPostForm
    template_name = 'post_photo.html'
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):                        #post後のやつ
    template_name = 'post_success.html'

class CategoryView(ListView):                               #カテゴリ
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        category_id = self.kwargs['category']
        return PhotoPost.objects.filter(category=category_id).order_by('-posted_at')

class UserView(ListView):                                   #ユーザー
    template_name = 'index.html'
    paginate_by = 9

    def get_queryset(self):
        user_id = self.kwargs['user']
        return PhotoPost.objects.filter(user=user_id).order_by('-posted_at')

class DetailView(DetailView):                               #お気に入り投稿のやつ
    template_name = 'detail.html'
    model = PhotoPost

class MypageView(ListView):                                 #マイページ
    template_name = 'mypage.html'
    paginate_by = 9

    def get_queryset(self):
        return PhotoPost.objects.filter(user=self.request.user).order_by('-posted_at')

class PhotoDeleteView(DeleteView):                          #
    model = PhotoPost
    template_name = 'photo_delete.html'
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

class FavoriteView(ListView):
    template_name = 'favorite.html'
    queryset = PhotoPost.objects.order_by('-posted_at')
    paginate_by = 9

class InDetailView(ListView):
    template_name = 'In_detail.html'
    queryset = PhotoPost.objects.order_by('-posted_at')

class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('photo:contact')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        title = form.cleaned_data['title']
        message = form.cleaned_data['message']
        subject = f'お問い合わせ: {title}'
        message = f'送信者名: {name}\nメールアドレス: {email}\n件名: {title}\nメッセージ:\n{message}'
        from_email = 'admin@example.com'
        to_list = ['admin@example.com']
        email_message = EmailMessage(subject, message, from_email, to_list)
        email_message.send()
        messages.success(self.request, 'お問い合わせは正常に送信されました。')
        return super().form_valid(form)




def image_gallery(request):
    images = get_local_images()
    
    # ファイル名順にソート
    images.sort(key=lambda x: int(x['name'].split('.')[0]))
    
    # ページネーションの設定
    paginator = Paginator(images, 45)  # 1ページに45個の画像を表示（3列×15行）
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    return render(request, 'image_gallery.html', {'page_obj': page_obj})


from django.views.generic import ListView
from .models import ImageModel
from .forms import ImageSearchForm
import re

class ImageListView(ListView):
    model = ImageModel
    template_name = 'image_search_list.html'
    context_object_name = 'images'
    paginate_by = 30  # 1ページに表示するアイテム数

    def get_queryset(self):
        queryset = super().get_queryset()
        form = ImageSearchForm(self.request.GET)
        if form.is_valid():
            if form.cleaned_data['name']:
                queryset = queryset.filter(name__icontains=form.cleaned_data['name'])
            if form.cleaned_data['type']:
                queryset = queryset.filter(type=form.cleaned_data['type'])
            if form.cleaned_data['rarity']:
                queryset = queryset.filter(rarity=form.cleaned_data['rarity'])
            if form.cleaned_data['category']:
                queryset = queryset.filter(category=form.cleaned_data['category'])
        
        # ファイル名の数字部分でソート
        def extract_number(name):
            match = re.search(r'\d+', name)
            return int(match.group()) if match else float('inf')  # 数字がない場合は無限大を返す

        queryset = sorted(queryset, key=lambda x: extract_number(x.name))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ImageSearchForm(self.request.GET)
        return context

photo/templates/In_detail.html
<!-- ベーステンプレートを適用する -->                           <!--index詳細はこちら-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}ポケポケブログ{% endblock %}

    {% block contents %}
        <!-- タイトルとナビゲーションボタン -->
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
                <div class="col-lg-6 col-md-8 mx-auto">
                    <!-- タイトルと本文 -->
                    <h1 class="fw-light">以下、本サイトの機能です</h1>
                    <p>
                    全カード閲覧</p>
                    <p>
                    分類別カード閲覧</p>
                    <p>
                    カード検索</p>
                    <p>
                    お気に入りカード投稿,閲覧</p>
                    <p>
                    所持カード登録,閲覧</p>
                    <p class="lead text-">
                    ※投稿,登録機能,所持カード閲覧はログイン中のみ使用可能</p>
                </div>
            </div>
        </section>
    {% endblock %}

photo/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  </head>
  
  <body>
    <div class="d-flex" id="wrapper">
      <!-- Sidebar-->
      <div class="border-end bg-white" id="sidebar-wrapper">
        <div class="sidebar-heading border-bottom bg-light">ポケポケブログ</div>
        <div class="list-group list-group-flush">
          <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'photo:image_gallery' %}">カード一覧</a>
          <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'photo:image_list' %}">カード検索</a>
          <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'photo:favorite' %}">お気に入り</a>
          {% if user.is_authenticated %}
            <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'photo:post' %}">お気に入り投稿</a>
          {% endif %}
        </div>
      </div>
      <!-- Page content wrapper-->
      <div id="page-content-wrapper">
        <!-- Top navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
          <div class="container-fluid">
            <button class="btn btn-primary" id="sidebarToggle">メニュー</button>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                <li class="nav-item active"><a class="nav-link" href="{% url 'photo:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'photo:contact' %}">お問い合わせ</a></li>
                <li class="nav-item dropdown">
                  {% if user.is_authenticated %}
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">アカウント</a>
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'photo:mypage' %}">マイページ</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">ログアウト</a>
                    <a class="dropdown-item" href="{% url 'password_reset' %}">パスワードのリセット</a>
                  </div>
                  {% else %}
                  <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">アカウント</a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'accounts:login' %}">ログイン</a>
                      <a class="dropdown-item" href="{% url 'accounts:signup' %}">サインアップ</a>
                    </div>
                  {% endif %}
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- Page content-->
        <div class="container">
          {% block contents %}{% endblock  %}
        </div>
      </div>
    </div>
  <!-- Bootstrap core JS-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <!-- Core theme JS-->
  <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

photo/templates/detail.html
<!-- ベーステンプレートを適用する-->                                    <!--お気に入り>viewで表示--><!--画像詳細-->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}ポケポケブログ{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム-->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる-->
          <div class="col offset-3">
            <!-- タイトル -->
            <h2>{{object.title}}</h2>
            <!-- コメント -->
            <p>{{object.comment}}</p>
            <br>
            <!-- 投稿日時 -->
            <p>{{object.posted_at}}に投稿</p>
            <!-- 1枚目の写真 -->
            <p><img src="{{ object.image1.url }}"></img></p>
            <!-- 2枚目の写真が投稿されていたら表示する-->
            {% if object.image2 %}
              <p><img src="{{ object.image2.url }}"></img></p>
            {% endif %}
            
            <!-- 投稿写真がログイン中のユーザーのものであれば削除ボタンを表示-->
            {% if request.user == object.user %}
            <form method="POST">
            <!-- リンク先のURL
                 photo/<Photo postsテーブルのid値>/delete/-->
            <a href="{% url 'photo:photo_delete' object.pk %}"
               class="btn btn-primary my-2">削除する</a>
            {% endif %}
            
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/favorite.html
<!-- ベーステンプレートを適用する -->                                       <!-- お気に入り -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}ポケポケブログ{% endblock %}

      {% block contents %}
        <!-- タイトルとナビゲーションボタン -->
        <section class="py-5 text-center container">
            <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <!-- タイトルと本文 -->
                <h1 class="fw-light">お気に入り</h1>
                <p class="lead text-muted">
                お気に入りのカードを</p>
                <p class="lead text-muted">
                コメントを添えて投稿することができます！</p>
                <p>
                <!-- ナビゲーションボタン -->
                {% if user.is_authenticated %}
                <!-- ログイン中のボタン -->
                <a href="{% url "photo:post" %}"
                    class="btn btn-primary my-2">投稿する</a>
                {% else %}
                <p>※投稿するにはログインしてください</p>
                <a href="{% url 'accounts:login' %}"
                class="btn btn-primary my-2">ログインはこちら</a>
                {% endif %}
                </p>
            </div>
            </div>
        </section>

      <!-- 投稿一覧テンプレートの組み込み -->
      {% include "photos_list.html" %}
      {% include "pagination.html" %}

      
      {% endblock %}

photo/templates/image_gallery.html
{% extends 'base.html' %}                                       <!-- カード一覧 -->

{% block title %}ポケポケブログ{% endblock %}

{% block contents %}
<!DOCTYPE html>
<html>
<head>
    <title>カード一覧</title>
    <style>
        .gallery {
            display: grid;
            grid-template-columns: repeat(3, 1fr);  /* 横に3つ表示 */
            gap: 10px;
            justify-content: center;
        }
        .gallery-item {
            text-align: center;
        }
        .gallery img {
            width: 300px;  /* 画像の幅を200pxに設定 */
            height: auto;
        }
    </style>
</head>
<body>
    <h1>カード一覧</h1>
    <div class="gallery">
        {% for image in page_obj %}
            <div class="gallery-item">
                <a href="{{ image.url }}" target="_blank">
                    <img src="{{ image.url }}" alt="{{ image.name }}">
                </a>
                <h2>{{ card.name }}</h2>
            </div>
        {% endfor %}
    </div>
    {% include 'pagination.html' %}
</body>
</html>
{% endblock %}

photo/templates/index.html
<!-- ベーステンプレートを適用する -->                                         <!-- ホーム -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}ポケポケブログ{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートの組み込み -->
      {% include "photos_title.html" %}

      <!-- 投稿一覧テンプレートの組み込み -->

      
      {% endblock %}

photo/templates/mypage.html
<!-- ベーステンプレートを適用する-->                                <!-- マイページ -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する-->
{% block title %}マイページ{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートは組み込まない-->
      
      <!-- ユーザーの投稿件数を表示-->
      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}さんのマイページ</h4>
          {% if object_list.count == 0 %}
            <p>{{user.username}}さんの投稿はありません</p>
          {% else %}
            <p>投稿<strong>{{object_list.count}}</strong>件</p>
          {% endif %}
          <a href="{% url 'photo:post' %}">投稿する</a>
        </div>
        <hr>
      {% endif %}
      
      <!-- 投稿一覧テンプレートの組み込み-->
      {% include "photos_list.html" %}
        
      <!-- ページネーションの組み込み-->
      {% include "pagination.html" %}

      {% endblock %}

photo/templates/photo_delete.html
<!-- ベーステンプレートを適用する -->         <!-- お気に入り投稿を削除 -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}ポケポケブログ{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-3を入れる -->
          <div class="col offset-3">
            <form method="POST">
              <br>
              <p>削除してもいいですか?</p>
              {% csrf_token %}
              <button class="btn btn-primary my-2"
                      type="submit">削除</button>
              <a href="{% url 'photo:photo_detail' object.pk %}"
                 class="btn btn-secondary my-2">キャンセル</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

photo/templates/photos_list.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>お気に入り</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for record in object_list %}
                <div class="col">
                    <div class="card shadow-sm">
                        <img src="{{ record.image1.url }}" 
                             class="bd-placeholder-img card-img-top"
                             width="100%" height="auto"
                             xmlns="http://www.w3.org/2000/svg"
                             role="img" aria-label="Placeholder: Thumbnail"
                             preserveAspectRatio="xMidYMid slice"
                             focusable="false">
                        <div class="card-body">
                            <p class="card-text">{{record.title}}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button"
                                            class="btn btn-sm btn-outline-secondary"
                                            onclick="location.href='{% url "photo:photo_detail" record.pk %}'">
                                            View</button>
                                    <button type="button"
                                            class="btn btn-sm btn-outline-secondary"
                                            onclick="location.href='{% url "photo:photos_cat" category=record.category.id %}'">
                                            {{record.category.title}}</button>
                                </div>
                                <a href="{% url "photo:user_list" user=record.user.id %}">
                                    <small class="text-muted">{{record.user.username}}</small>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:30 %}
                </div><div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

photo/templates/post_success.html
<!-- ベーステンプレートを適用する -->                                       <!-- お気に入り投稿後に表示 -->
{% extends 'base.html' %}

<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Post Success{% endblock %}

      {% block contents %}
      <!-- Bootstrapのグリッドシステム -->
      <br><br>
      <div class="container">
        <!-- 行を配置 -->
        <div class="row">
          <!-- 列の左右に余白offset-2を入れる -->
          <div class="col offset-2">
            <h4>投稿が完了しました!</h4>
            <p><a href="{% url 'photo:post' %}">続けて投稿</a><p>
            <p><a href="{% url 'photo:index' %}">Back to Top</a><p>
          </dv>
        </dv>
      </dv>
      {% endblock %}